import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/auth/session-provider";
import { SideBar } from "../components/ui/side-bar";
import ThemeProvider from "../components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const organizations = [
    { name: "Epitech" },
    { name: "PoC" },
    { name: "PoC Services" },
  ];
  const currentOrg = { name: "Personal" };

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {session && (
            <SideBar
              organizations={organizations}
              currentOrg={currentOrg}
            />
          )}
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}