import { SideBar } from "@/components/ui/side-bar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const organizations = [{name: "Epitech"},
        {name: "PoC"}, {name: "PoC Services"}
      ]
    const currentOrg = {name: "Personal"}

    return (
        <html lang="en">
            <body>
                {children}
                <SideBar organizations={organizations} currentOrg={currentOrg}></SideBar>
            </body>
        </html>
    )
}
